services:
  app:
    build: .
    container_name: telco_app
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: telco_churn_db
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: telco_db
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: